### ISSUE TITLE
Option to group `bwscaling` results by memory domains

### ISSUE THREAD

**Issue by carstenbauer** [JuliaPerf/BandwidthBenchmark.jl#10]
Originally filed by @giordano over at https://github.com/carstenbauer/ThreadPinning.jl/issues/36.

Currently `bwscaling`
* leaves it up to the user to pin threads correctly
* provides results like [this](https://github.com/giordano/julia-on-fugaku/blob/cd5795aa746ec83286dc5d82aefdde50c56f74a3/benchmarks/bandwidthbenchmarkjl/bwscaling.pdf) (for all kernels)

In https://github.com/RRZE-HPC/TheBandwidthBenchmark/wiki/Fujitsu-FX700-S1-M4-C48, they also have output that is grouped by memory domains, see output below "Results for scaling across memory domains.", which is visualized figures (except the first) at the bottom. Maybe we could add something like this as well.

**Comment by carstenbauer** [comment]
@giordano, see https://github.com/JuliaPerf/BandwidthBenchmark.jl/tree/main/benchmarks/noctua_pc2/bwscaling_memdomain and in particular the output https://github.com/JuliaPerf/BandwidthBenchmark.jl/blob/carstenbauer/issue10/benchmarks/noctua_pc2/bwscaling_memdomain/bwscaling-memdomain-sdaxpy.pdf which matches expectations (100 GB/s for 1 and 200 GB/s for 2 domains). This is on Noctua 1 which only has 2 memory domains, one per socket/CPU.

**Comment by giordano** [comment]
Awesome, thanks!  I'll try to rerun the benchmarks later this week!

**Comment by giordano** [comment]
Uhm, on Ookami this is crashing with
```
ERROR: LoadError: Memory domains have different number of cores. This is currently unsupported.
Stacktrace:
 [1] bwscaling_memory_domains(; max_nnuma::Int64, max_nthreads::Int64, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ BandwidthBenchmark ~/.julia/packages/BandwidthBenchmark/0cuuE/src/bwscaling.jl:40
 [2] bwscaling_memory_domains()
   @ BandwidthBenchmark ~/.julia/packages/BandwidthBenchmark/0cuuE/src/bwscaling.jl:34
 [3] top-level scope
   @ ~/repo/julia-on-fugaku/benchmarks/bandwidthbenchmarkjl/bench.jl:22
in expression starting at /lustre/home/mosgiordano/repo/julia-on-fugaku/benchmarks/bandwidthbenchmarkjl/bench.jl:22
```
but there should be 12 cores for each of the 4 regions  :confused:  Yes, I started Julia with `-t 48`.  Can `pinthreads(:scatter; places=:numa)` be problematic here?

**Comment by carstenbauer** [comment]
That's weird. Until I have access to Ookami, what does `ThreadPinning.lscpu()` or, equivalently, `lscpu --all --extended` give?

**Comment by carstenbauer** [comment]
@giordano Should be fixed on master, there was a bug in the if condition. Would still be nice to get the lscpu output.

**Comment by carstenbauer** [comment]
> Can `pinthreads(:scatter; places=:numa)` be problematic here?

No, `bwscaling_memory_domains` pins threads internally, i.e., overwrite whatever pinning the user did beforehand.

**Comment by giordano** [comment]
Working great now, thanks!

![bwscaling-memdomain-update](https://user-images.githubusercontent.com/765740/207309344-5ed39450-e092-43ed-8850-00ce45a32afa.png)

```console
$ lscpu --all --extended
CPU NODE CLUSTER CORE ONLINE
0   0    0       0    yes
1   0    0       1    yes
2   0    0       2    yes
3   0    0       3    yes
4   0    0       4    yes
5   0    0       5    yes
6   0    0       6    yes
7   0    0       7    yes
8   0    0       8    yes
9   0    0       9    yes
10  0    0       10   yes
11  0    0       11   yes
12  1    1       12   yes
13  1    1       13   yes
14  1    1       14   yes
15  1    1       15   yes
16  1    1       16   yes
17  1    1       17   yes
18  1    1       18   yes
19  1    1       19   yes
20  1    1       20   yes
21  1    1       21   yes
22  1    1       22   yes
23  1    1       23   yes
24  2    2       24   yes
25  2    2       25   yes
26  2    2       26   yes
27  2    2       27   yes
28  2    2       28   yes
29  2    2       29   yes
30  2    2       30   yes
31  2    2       31   yes
32  2    2       32   yes
33  2    2       33   yes
34  2    2       34   yes
35  2    2       35   yes
36  3    3       36   yes
37  3    3       37   yes
38  3    3       38   yes
39  3    3       39   yes
40  3    3       40   yes
41  3    3       41   yes
42  3    3       42   yes
43  3    3       43   yes
44  3    3       44   yes
45  3    3       45   yes
46  3    3       46   yes
47  3    3       47   yes
```

**Comment by carstenbauer** [comment]
> although it looks like there is some drop in performance by increasing number of domains

Huh? Maybe I'm missing something but the purple line uses all 4 memory domains and obtains the highest memory bandwidth, as expected.

**Comment by giordano** [comment]
That's not 4x the performance of 1 domain though, it's slightly less, compare with the update scaling at https://github.com/RRZE-HPC/TheBandwidthBenchmark/wiki/Fujitsu-FX700-S1-M4-C48

**Comment by carstenbauer** [comment]
Ah, that's what you mean (you didn't say what you're comparing to and also not that this is the update kernel 😉). Indeed, this is interesting... Would be nice to have the script that they run to see if they do something differently. Maybe I can ask them.
