### ISSUE TITLE
Allow running bandwidth benchmarks with different kernels

### ISSUE THREAD

**Issue by carstenbauer** [JuliaPerf/BandwidthBenchmark.jl#9]
From https://github.com/carstenbauer/ThreadPinning.jl/issues/35. (cc @giordano)

> Follow up from https://github.com/giordano/julia-on-fugaku/issues/1: it'd be nice to allow running bwscaling (and necessarily also bwbench) with kernels other than sdxapy. This would allow comparing results with [RRZE-HPC/TheBandwidthBenchmark](https://github.com/RRZE-HPC/TheBandwidthBenchmark), which basically reports scaling all other kernels but sdaxpy: init, sum, copy, update, triad. Example: [Fujitsu FX700 S1 M4 C48](https://github.com/RRZE-HPC/TheBandwidthBenchmark/wiki/Fujitsu-FX700-S1-M4-C48).

**Comment by carstenbauer** [comment]
I'll implement this if I find the time (maybe later today). On a more general note, the kernels that they run are the conventional STREAM kernels which are implemented in STREAMBenchmark.jl. The latter provides the function `scaling_benchmark`, which is very similar to `bwbench` here. I created an [issue](https://github.com/JuliaPerf/STREAMBenchmark.jl/issues/19) over there to expand the options of this function as well.

**Comment by carstenbauer** [comment]
Implemented on master where you can do, e.g., `bwscaling(; kernel=:triad). Allowed kernels are init, copy, update, triad, daxpy, striad, and sdaxpy, provided either as string or symbol.

However, I realized that the current implementation always runs all kernels anyways and only *selects* the results of the specified one. I think the best thing here is to just return the scaling of all kernels in a big table rather than specifying a single one.

**Comment by carstenbauer** [comment]
Alright, `bwscaling` now returns the scaling results for all kernels (I dropped the `kernel` kwarg again).

**Comment by giordano** [comment]
New run of bwscaling with all the kernels: https://github.com/giordano/julia-on-fugaku/tree/5d86cdfc8c7bb2c51515cd2babc0e2561e47a00c/benchmarks/bandwidthbenchmarkjl (I'll eventually move this to the `julia-on-ookami` repo, and update in this repository the results on Fugaku).  Julia is always slightly behind the results in https://github.com/RRZE-HPC/TheBandwidthBenchmark/wiki/Fujitsu-FX700-S1-M4-C48, but they use the vendor compiler optimised with `-Kfast` (the equivalent of `-Ofast` in gcc/clang), so I'd say the difference isn't too bad.  We match ups and downs in their report for the directly comparable benchmarks (init, copy, update, triad), that's good.
